repos:
  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: /opt/homebrew/opt/llvm/bin/clang-tidy
        args:
          - -p
          - build
          - --extra-arg=-isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
        language: system
        files: ^src/.*\.(cpp|cxx)$
